@startuml architecture

component core {
  package beastbook.core
  package beastbook.json
}

component fxui {
  package beastbook.fxui
}

component rest {
  package beastbook.server
  package beastbook.client
}

component jackson

component javafx {
  component fxml
}

beastbook.fxui ..> javafx
beastbook.fxui ..> fxml
beastbook.fxui ..> beastbook.core
beastbook.fxui ..> beastbook.json

beastbook.core ..> beastbook.json
beastbook.json ..> jackson

beastbook.server ..> beastbook.core
beastbook.server ..> beastbook.json

beastbook.client ..> beastbook.core

@enduml