@startuml architecture

component core {
  package beastbook.core
  package beastbook.json
}

component fxui {
  package beastbook.fxui
}

component rest {
  package beastbook.server
  package beastbook.client
}

component jackson

component javafx {
  component fxml
}

beastbook.fxui ..> javafx
beastbook.fxui ..> fxml
beastbook.fxui ..> beastbook.core
beastbook.fxui ..> beastbook.client
/'
beastbook.core ..> beastbook.json
'/
beastbook.json ..> jackson
beastbook.json ..> beastbook.core


beastbook.server ..> beastbook.core
beastbook.server ..> beastbook.json

beastbook.client ..> beastbook.server
beastbook.client ..> beastbook.core

@enduml