@startuml Core Diagram
scale 1

interface IdClasses

core -- Exercise
core -- User
core -- History
core -- Workout
core -- IdHandler
core -- Exceptions
core -- Properties
core -- IdClasses
core -- Validation
@enduml