@startuml Class Diagram
scale 1
/' Not Classes, but fxml files  '/

fxui -- resources
resources -- Login

Login -- Homescreen
Homescreen -- Create
Homescreen -- WorkoutOverview
Homescreen -- HistoryOverview

WorkoutOverview -- Workout
HistoryOverview -- History
@enduml