@startuml Fxui Diagram
class HistoryController extends AbstractController{
  -TableView<Exercise> historyTable
  +void setTable(History)
}

class HistoryOverviewController {
  -loadTable()
  ~loadHistory(ActionEvent)
  ~deleteHistory()
}

class CreateWorkoutController {
  +updateTable()
  ~addExercise()
  ~loadWorkout(ActionEvent)
  ~createWorkout()
  ~deleteExercise()
}

abstract class AbstractController {
  - String: username
  - String: password
  # ClientController: service 

  ~void loadHome(ActionEvent)
  ~void loadLogin(ActionEvent)
  ~void loadCreate(ActionEvent)
  ~void loadOverview(ActionEvent)
  ~void loadHistoryOverview(ActionEvent)
}

class WorkoutController {
  +updateTable()
  ~saveHistory()
  -editTable()
}

class WorkoutOverviewController {
  -loadTable()
  ~loadWorkout(ActionEvent)
  ~deleteWorkout()
}

class LoginController extends AbstractController{
  ~void registerUser()
  ~void loginUser()
}

class HomeScreenController extends AbstractController{
  ~void deleteUser()
}

class App {
  +void start(Stage)
}

fxui -- AbstractController
fxui -- App

@enduml