@startuml Json Diagram
class BeastBookPersistence {
  -void writeObjectToFile(Object, File)
  -Object readObjectFromFile(File, Class)
  -void deleteFile(File)
  +void saveIdObject(IdClasses)
  -void deleteIdObject(String, Class)
}

class ExerciseDeserializer {
  +History deserialize(JsonParser, DeserializationContext)
  ~History deserialize(JsonNode)
  +String getExercise
}

class ExerciseSerializer {
  +void serialize(Exercise, JsonGenerator, SerializerProvider)
}

class UserDeserializer {
}

class UserSerializer {
}

class WorkoutDeserializer {
}

class WorkoutSerializer {
}

class HistoryDeserializer {
}

class HistorySerializer {
}

class IdHandlerDeserializer {
}

class IdHandlerSerializer {
}

class BeastBookModule {

}

json -- internal
internal -- ExerciseDeserializer
internal -- ExerciseSerializer
internal -- UserDeserializer
internal -- UserSerializer
internal -- WorkoutDeserializer
internal -- WorkoutSerializer
internal -- HistoryDeserializer
internal -- HistorySerializer
internal -- IdHandlerDeserializer
internal -- IdHandlerSerializer
internal -- BeastBookModule
json -- BeastBookPersistence
@enduml