@startuml Core Diagram
scale 1
rest -- client
rest -- server
rest -- ServerApplication

client -- ClientService
client -- ClientController
client -- RegisterController
server -- ServerService
server -- ServerController
server -- Rules
@enduml
